### ISSUE TITLE
Story_graph.py remove as its broken

### ISSUE THREAD

**Issue by EatingBacon** [EatingBacon/gameprog-detective-server#65]

**Comment by robinwersich** [comment]
```
Traceback (most recent call last):
  File "/home/robin/Dev/detective_game/gameprog-detective-server/.venv/lib/python3.8/site-packages/graphviz/backend.py", line 159, in run
    proc = subprocess.Popen(cmd, startupinfo=get_startupinfo(), **kwargs)
  File "/usr/lib/python3.8/subprocess.py", line 854, in __init__
    self._execute_child(args, executable, preexec_fn, close_fds,
  File "/usr/lib/python3.8/subprocess.py", line 1702, in _execute_child
    raise child_exception_type(errno_num, err_msg, err_filename)
FileNotFoundError: [Errno 2] No such file or directory: 'dot'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "visualize_story_graph.py", line 38, in <module>
    main()
  File "visualize_story_graph.py", line 34, in main
    story_graph.view()
  File "/home/robin/Dev/detective_game/gameprog-detective-server/.venv/lib/python3.8/site-packages/graphviz/files.py", line 240, in view
    return self.render(filename=filename, directory=directory,
  File "/home/robin/Dev/detective_game/gameprog-detective-server/.venv/lib/python3.8/site-packages/graphviz/files.py", line 207, in render
    rendered = backend.render(self._engine, format, filepath,
  File "/home/robin/Dev/detective_game/gameprog-detective-server/.venv/lib/python3.8/site-packages/graphviz/backend.py", line 206, in render
    run(cmd, capture_output=True, cwd=cwd, check=True, quiet=quiet)
  File "/home/robin/Dev/detective_game/gameprog-detective-server/.venv/lib/python3.8/site-packages/graphviz/backend.py", line 162, in run
    raise ExecutableNotFound(cmd)
graphviz.backend.ExecutableNotFound: failed to execute ['dot', '-Tpdf', '-O', 'Story.gv'], make sure the Graphviz executables are on your systems' PATH
```

So the problem probably is that if graphviz is only installed in the venv there seem to be missing some executables
(also setting the GP_TELEGRAM_TOKEN etc. is required to get the story file from the config which seems stupid but whatever)

**Comment by robinwersich** [comment]
could you try to uninstall graphviz from your system and only install it via `manage.sh install` ?
